<div id="game-menu">
  <div id="menu-content">
      <div class="input radio-as-buttons">
          <?php foreach(app(\App\Models\Player::class)->getViewTypeOptions($this->getData('player')) as $id => $viewType): ?>
              <?php $selected = $viewType['selected'] ? 'checked' : '' ?>
              <input type="radio" id="view_type-<?= $id ?>" name="view_type" value="<?= $viewType['value'] ?>" onclick="updateViewType(this)" <?= $selected ?>>
              <label for="view_type-<?= $id ?>"><?= $viewType['label'] ?></label>
          <?php endforeach ?>
      </div>
        <a href="game/exit" class="button danger">Opuść grę</a>
  </div>
  <a href="#" class="hamburger-icon" onclick="toogleMenu()">
    <i class="fa fa-bars"></i>
  </a>
</div>
<div id="game-content">
    <div id="game-name">
      Gra #<?= $this->getData('game')->id ?>
    </div>
    <div id="section-result">
    </div>
    <div id="section-question">
    </div>
</div>
<script>
function action(actionUrl)
{
    $.ajax({
        type : 'GET',
        url : actionUrl,
    });
}
function toogleMenu() {
    var menuContent = $('#menu-content');
    menuContent.toggle();
}
function updateViewType(elem) {
    if (elem.checked) {
        $.ajax({
            type: 'GET',
            url: '<?= url('player/updateGameView?view_type=') ?>' + elem.value
        });
    }
}
</script>