<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="pub/css/quiz.css">
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
        <script src="pub/js/game.js"></script>
    </head>
    <body>
        <div class="container">
            <?= $this->getChild('content') ?>
        </div>
    </body>
</html>