<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="<?= url('pub/css/quiz12.css') ?>">
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
        <?php foreach ($this->js as $js): ?>
            <script src="<?= $js ?>" type="text/javascript"></script>
        <?php endforeach?>
    </head>
    <body>
        <div class="container">
            <?= $this->getChild('content') ?>
        </div>
    </body>
</html>