<form id="form" method="post" action="create">
    <input type="submit" value="Stwórz" id="button-ready">
    <?php
        $providers = app(\App\Models\Game::class)->getQuestionProviders();
    ?>
    <div id="quiz-checkboxes">
        <?php foreach ($providers as $providerId => $provider): ?>
            <input type="checkbox" 
                id="provider-<?= $providerId ?>" 
                name="questions[<?= $providerId ?>][selected]" 
                value="1"
                onclick="providerSelected(this)">
            <label for="provider-<?= $providerId ?>"><?= $provider->label ?></label>
            <div id="provider-<?= $providerId ?>-options" class="question-provider-options" style="display:none">
                <div class="question-set-priority">
                    <div class="button" onclick="updatePriority('<?= $providerId ?>', -10)">-10</div>
                    <div class="button" onclick="updatePriority('<?= $providerId ?>', -1)">-</div>
                    <div class="value">
                        Priorytet:
                        <input type="text" id="priority-<?= $providerId ?>" name="questions[<?= $providerId ?>][priority]" value="<?= $provider->defaultPriority ?>" readonly>
                    </div>
                    <div class="button" onclick="updatePriority('<?= $providerId ?>', 1)">+</div>
                    <div class="button" onclick="updatePriority('<?= $providerId ?>', 10)">+10</div>
                </div>
                <?php if ($optionsBlock = $provider->getOptionsBlock(['provider_id' => $providerId])): ?>
                    <?= $optionsBlock->getHtml() ?>
                <?php endif ?>
            </div>
        <?php endforeach ?>
    </div>
</form>
<script>
function providerSelected(elem) {
    let optionsContenerId = elem.id + "-options";
    if (elem.checked) {
        $("#" + optionsContenerId).show();
    } else {
        $("#" + optionsContenerId).hide();
    }
}
function updatePriority(providerId, value) {
    let elem = $("#priority-" + providerId);
    let newPriority = parseInt(elem.val()) + parseInt(value);
    if (newPriority < 1) {
        newPriority = 1;
    }
    if (newPriority > 100) {
        newPriority = 100;
    }
    elem.val(newPriority);
}
</script>