<form id="form" method="post" action="create">
    <input type="submit" value="Stwórz" id="button-ready">
    <?php
        $providers = app(\App\Models\Game::class)->getQuestionProviders();
    ?>
    <div id="quiz-checkboxes">
        <?php foreach ($providers as $providerId => $provider): ?>
            <input type="checkbox" 
                id="provider-<?= $providerId ?>" 
                name="questions[<?= $providerId ?>][selected]" 
                value="1"
                onclick="providerSelected(this)">
            <label for="provider-<?= $providerId ?>"><?= $provider->label ?></label>
            <div id="provider-<?= $providerId ?>-options" class="question-provider-options" style="display:none">
                <?php if ($optionsBlock = $provider->getOptionsBlock(['provider_id' => $providerId])): ?>
                    <?= $optionsBlock->getHtml() ?>
                <?php endif ?>
            </div>
        <?php endforeach ?>
    </div>
</form>
<script>
function providerSelected(elem) {
    let optionsContenerId = elem.id + "-options";
    if (elem.checked) {
        $("#" + optionsContenerId).show();
    } else {
        $("#" + optionsContenerId).hide();
    }
}
</script>