<?php
$game = $this->getData('game');
$question = $this->getData('question');
$questionImage = $question['question_image'] ?? false;
?>
<div id="question-header">Pytanie numer: <span id="question-number"><?= $game->round ?></span></div>
<?php if ($this->getData('show_question')): ?>
    <div id="question-text">
        <?= $question['question-prefix'] ?? '' ?> <?= $question['question'] ?>
        <?php if ($questionImage): ?>
            <div><img src="<?= url('media/' . $questionImage ?? '') ?>"></div>
        <?php endif ?>
    </div>
<?php endif ?>
<?php if ($this->getData('show_answers')): ?>
    <div id="section-answers">
        <div id="answers-list">
            <?php foreach ($question['answers'] as $id => $answer): ?>
                <div class="answer <?= $answer['class'] ?>" data-index="<?= $id ?>"><?= $answer['answer'] ?></div>
            <?php endforeach ?>
        </div>
    </div>
<?php endif ?>
<div id="question-footer">
    <?php if ($question['save_as'] ?? false): ?>
    <a href="#" onclick="saveQuestion()" class="button">Zapisz pytanie</a>
    <?php endif ?>
</div>