<?php
$player = $this->getData('player');
?>
<a href="." class=back>Wróć</a>
<form id="select-game-form" method="post">
    <input type="hidden" name="game_id" id="game_id"/>
    <div class="row input">
        <label for="name">Twoje imie</label>
        <div class="input">
            <input type="text" id="name" name="name" placeholder="Twoje imię ..." value="<?= $player->name ?? '' ?>" required>
        </div>
    </div>
        <div class="row input">
        <label for="name">Widok</label>
        <div class="input radio-as-buttons">
            <?php foreach($this->getData('view_types') as $id => $viewType): ?>
                <?php $selected = $viewType['selected'] ? 'checked' : '' ?>
                <input type="radio" id="view_type-<?= $id ?>" name="view_type" value="<?= $viewType['value'] ?>" <?= $selected ?>>
                <label for="view_type-<?= $id ?>"><?= $viewType['label'] ?></label>
            <?php endforeach ?>
        </div>
    </div>
    <div class="row button">
        <div></div>
        <a href="#" onclick="selectGame('game/form', 0)" class="button primary">Nowa Gra</a>
    </div>
    <?php foreach($this->getData('active_games') as $game): ?>
        <div class="row button">
            <div></div>
            <a href="#" onclick="selectGame('game/join', <?= $game['id'] ?>)" class="button">Gra #<?= $game['id'] ?>: <?= $game['creator'] ?></a>
        </div>
    <?php endforeach ?>
</form>
<script>
    function selectGame(action, gameId)
    {
        let form = $("#select-game-form");
        form[0].action = action;
        if (form[0].checkValidity()) {
            $("#game_id").val(gameId);
            form[0].submit();
        } else {
            form[0].reportValidity();
        }
    }
</script>