<a href="." class=back>Wróć</a>
<form id="form" method="post">
    <input type="hidden" name="game_id" id="game_id"/>
    <div class="row">
        <div class="col-25 text-right">
            <label for="name">Twoje imie</label>
        </div>
        <div class="col-75">
            <input type="text" id="name" name="name" placeholder="Twoje imię ..." required>
        </div>
        <table>
            <tr>
                <td class="center-container">
                    <a href="#" onclick="selectGame('game/form', 0)" class="primary">Nowa Gra</a>
                </td>
            </tr>
            <?php foreach($this->getData('active_games') as $game): ?>
                <tr>
                    <td class="center-container">
                        <a href="#" onclick="selectGame('game/join', <?= $game['id'] ?>)" class="primary"><?= $game['creator'] ?></a>
                    </td>
                </tr>
            <?php endforeach ?>
        </table>
    </div>
</form>
<script>
    function selectGame(action, gameId)
    {
        let form = $("#form");
        form[0].action = action;
        if (form[0].checkValidity()) {
            $("#game_id").val(gameId);
            form[0].submit();
        } else {
            form[0].reportValidity();
        }
    }
</script>