<?php
$question = $this->getData('question');
?>
<a href="quizForm?id=<?= $this->getData('quiz_id') ?>" class=back>Wróć</a>
<form id="edit-form" method="post" action="saveQuestion">
    <input type="hidden" name="quiz" value="<?= $this->getData('quiz_id') ?>" />
    <input type="hidden" name="id" value="<?= $this->getData('question_id') ?? '' ?>" />
    <div class="row row-2 question">
        <label for="question">Pytanie</label>
        <div class="input">
            <div class="text-option">
                <textarea name="question" required placeholder="Pytanie.." style="height:200px"><?= $question['question'] ?? '' ?></textarea>
            </div>
        </div>
        <div class="input">
            <?php $questionImage = $question['question_image'] ?? false ?>
            <input type="text" placeholder="Image URL.." name="question-image" value="<?= $questionImage['url'] ?? '' ?>">
            <?php if ($questionImage): ?>
                <img src="<?= url('media/' . ($questionImage['path'] ?? '')) ?>">
            <?php endif ?>
        </div>
    </div>
    <div class="row">
        <label for="answer">Poprawna Odpowiedź</label>
        <div class="input">
            <textarea id="answer" name="answer" required placeholder="Poprawna Odpowiedź.." style="height:200px"><?= $question['answer'] ?? '' ?></textarea>
        </div>
    </div>
    <div class="row">
        <label for="answer">Błędne Odpowiedzi</label>
        <div class="input" id="wrong_answers_list">
            <?php $wrongAnseresCounter = 0 ?>
            <?php foreach($question['wrong_answers'] ?? [] as $wrongAnswer): ?>
                <div>
                    <textarea id="wrong_answer_<?= $wrongAnseresCounter ?>" 
                        name="wrong_answer[<?= $wrongAnseresCounter ?>]" 
                        <?php if ($wrongAnseresCounter == 0): ?>required<?php endif ?>
                        placeholder="Błędna Odpowiedź..." 
                        style="height:200px"><?= $wrongAnswer ?></textarea>
                </div>
                <?php $wrongAnseresCounter ++ ?>
            <?php endforeach ?>
        </div>
    </div>
    <div class="row">
        <div></div>
        <a href="#" onclick="addWrongAnser(); event.preventDefault();">Dodaj Odpowiedź</a>
    </div>
    <div class="row">
        <div></div>
        <input type="submit" value="Zapisz">
    </div>
</form>
<div id="wrong_answer_template" style="display: none">
    <div>
        <textarea id="" name="" placeholder="Błędna Odpowiedź..." style="height:200px"></textarea>
    </div>
</div>
<script>
var wrong_answers_count = <?= $wrongAnseresCounter ?>;
function addWrongAnser()
{
    var wrongAnswersList = $('#wrong_answers_list');
    var newWrongAnser = $('#wrong_answer_template').children().clone(true);
    newWrongAnser.find("textarea").attr("id", "wrong_answer_" + wrong_answers_count);
    newWrongAnser.find("textarea").attr("name", "wrong_answer[" + wrong_answers_count + "]");
    wrongAnswersList.append(newWrongAnser);
    wrong_answers_count ++;
}
</script>