<a href="quizList" class="back">Wróć</a>
    <form method="post" action="saveQuiz">
    <input type="hidden" name="id" value="<?= $this->getData('id') ?>" />
    <div class="row">
        <div class="col-25 text-right">
            <label for="name">Nazwa</label>
        </div>
        <div class="col-75">
            <input type="text" id="name" name="name" value="<?= $this->getData('name') ?>" placeholder="Nazwa Quizu ..." required>
        </div>
    </div>
    <div class="row">
        <input type="submit" value="Zapisz">
    </div>
</form>
<?php if ($this->getData('id')): ?>
    <div class="row">
        <div class="col-25 text-right">
            <label>Ilość pytań</label>
        </div>
        <div class="col-75">
        <label><?= \App\Models\Quiz::getQuestionsCount($this->getData('id')) ?></label>
        </div>
    </div>
    <div class="row">
        <div class="col-25 text-right">
        <a href="questionForm?quiz=<?= $this->getData('id') ?>" class="button primary">Dodaj pytanie</a>
        </div>
        <div class="col-75 text-left">
            <a href="questionList?quiz=<?= $this->getData('id') ?>" class="button">Pokaż Pytania</a>
        </div>
    </div>
<?php endif ?>
